"""Author two independent iteration-one recipes. Existing recipes are never overwritten."""
import json,hashlib,shutil
from pathlib import Path
GAME=Path(__file__).resolve().parents[1]
ART=GAME.parent/'brutalist.art'
WALK=GAME/'youtube/claude-liam-walker-jumpman-clawd-walkthrough'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,x):p.write_text(json.dumps(x,indent=2)+'\n')
for kind in ['walkthrough','gamedev']:
    root=GAME/'youtube'/f'claude-liam-walker-jumpman-clawd-{kind}'
    if (root/'beat_sheet.json').exists():raise SystemExit('Preserving existing recipe: '+str(root))
    for part in ['media','mp3','audio','evidence','exports/landscape','_qc','remotion/src','remotion/public','scripts']:(root/part).mkdir(parents=True,exist_ok=True)
    for name,src in [('EBGaramond-Regular.ttf','EB_Garamond/static/EBGaramond-Regular.ttf'),('Inter-Regular.ttf','Inter/static/Inter_28pt-Regular.ttf'),('PTMono-Regular.ttf','PT_Mono/PTMono-Regular.ttf')]:shutil.copy2(ART/'runtime/fonts'/src,root/'remotion/public'/name)
    if not (root/'remotion/node_modules').exists():(root/'remotion/node_modules').symlink_to(ART/'runtime/remotion/node_modules',target_is_directory=True)
    if kind=='gamedev':
        for file in ['scripts/build.py','scripts/qc.py','remotion/src/index.tsx']:shutil.copy2(WALK/file,root/file)
    title='Clawd Takes the First Step' if kind=='walkthrough' else 'Building Clawd: One Change at a Time'
    beats=[];excerpts=[];pairs=[];features=[]
    def add(heading,text,pattern=None,props=None,take=None):
        bid=f'B{len(beats):02d}'
        shot={'type':'FOOTAGE' if take else 'REMOTION','source':'own','classification':'SHOW','visual_intent':heading,'show':[{'at':'beat','event':heading}]}
        if pattern:shot['remotion']={'pattern':pattern,'props':props or {}}
        if take:shot['evidence_media']=f'media/source-{take}.mp4'
        b={'beat_id':bid,'heading':heading,'narration_text':text,'engine':'kokoro','voice':'am_onyx','shot':shot}
        if take:b['gameplay_take']=take
        beats.append(b);return bid
    def board(heading,text,rows,note):return add(heading,text,'AssignmentBoard',{'title':heading,'rows':rows,'note':note})
    def code(heading,text,file,first,last,notes):
        lines=(GAME/'godot'/file).read_text().splitlines()
        start=next(i for i,l in enumerate(lines) if first in l)+1
        end=next(i for i in range(start-1,len(lines)) if last in lines[i])+1
        actual='\n'.join(lines[start-1:end])
        bid=add(heading,text,'GodotDevWorkbench',{'mode':'code','title':heading,'project':'walker-jumpman-clawd','path':file,'source':'Exact Clawd source · reconstructed editor · next: actual result','code':actual,'startLine':start,'codeFontSize':27,'notes':[{'label':k,'value':v} for k,v in notes],'output':['Source snapshot: evidence/source-build.json'],'cues':[]})
        # First line is highlighted after the introduction, a beat-local cue.
        beats[-1]['shot']['remotion']['props']['cues']=[{'at':1.0,'line':start,'label':heading}]
        excerpts.append({'beat_id':bid,'path':file,'start_line':start,'end_line':end,'text':actual})
        return bid
    def result(previous,heading,text,take):
        bid=add(heading,text,take=take)
        pairs.append({'code_beat':previous,'result_beat':bid,'observation':heading+'; native Godot output, scripted input or labelled diagnostic preview.','media':{'path':f'media/source-{take}.mp4'}})
        return bid
    def composer(prompt,segment):return {'command':prompt,'topic':'Suggested prompt · not a saved Claude conversation','segment':segment,'greeting':'Hello, Liam','runningText':'','output':[],'folderLabel':'walker-jumpman-clawd','modelLabel':'Claude Code','effortLabel':'','placeholder':''}
    prompt='Please use Walker to convert my game design document\nabout a coding-agent platformer into one small revision:\nput Clawd in the existing level. Preserve the mechanics.'
    add('Professor Bear starts Assignment 1',"Please use Walker to convert my game design document about a coding-agent platformer into one small revision: put Clawd in the existing level. Preserve the mechanics. I'm Liam, in for Professor Bear. His project is Walker Jumpman Clawd. The opening prompt is a suggested handoff, not a saved conversation.",'ClaudeComposerAsk',composer(prompt,title))
    add('One character, the same level',"We have changed the character, not completed the assignment. Clawd now moves through the existing First Steps level. The physics and layout remain the starter's. A separate gallery contains eighteen animations. Task mini-goals, new hazards, and the required level extension are later decisions. This is the first revision of a semester-long example.",'BrutalistHesitantWriter',{'text':'Build everything today.','triggerWords':'everything','replacementWords':'one change','fontSize':92,'mistakeRate':0,'hesitateWithin':0,'hesitateBetween':0,'charMs':60,'jitter':0,'seed':WALK.name,'face':'serif','align':'center'})
    beats[-1]['lead_silence_s']=.8
    board('The loop is one inspectable change',"Predict what might break. Build one change. Play it, inspect the evidence, revise, then record the version. Here the prediction is specific: Clawd's wide arms might make the unchanged collision box misleading. A small experiment gives us a question to answer. Changing the character, level, and physics together would make that answer harder to isolate.",[['Predict','Wide art may mislead collision judgment'],['Build and inspect','Character only; compare against the starter'],['Record and revise','Evidence → one next decision']], 'CHANGE-BRIEF.md · Walker: Brief → Build → Playtest → Inspect → Revise → Export')
    if kind=='walkthrough':
        for heading,text,take,feature in [
            ('Meet Clawd in the original course',"Here is the actual Godot level. Enter starts, left and right move, and the character stops after release. Clawd's legs now animate with movement; the ground and controls have not been redesigned. These are scripted normal-input captures, not Professor Bear's playtest. The first visual question is simple: can you read this character at game size?",'controls','movement-boundary-braking-opposing-inputs'),
            ('One body, one physical jump',"Watch the feet leave the ground and return. Holding Space does not bounce again on landing, and another press in the air does not create a double jump. The airborne drawing holds a pose while physics supplies the trajectory. An animation named jump must not secretly add another movement mechanic.",'jump','jump-held-no-double'),
            ('The arm is not the collision box',"This enlarged view uses the actual Godot drawing routine. The blue rectangle marks the unchanged eighteen by twenty-eight collision reference. Clawd's arms extend beyond it. That is a real first-pass tradeoff, not a solved design problem. Bear should test whether the mismatch feels forgiving or confusing before deciding on a second change.",'inspector','art-collider-diagnostic'),
            ('A mistake still returns control',"Into the spikes: failure, a brief error animation, one retry, then control returns at the start. We did not invent a new hazard system. The character's reaction is presentation, while the session still owns the reset. Watch the result before deciding whether that visual reaction explains enough.",'spike','hazard-retry'),
            ('Falling is a separate failure route',"Missing the gap still ends the attempt and starts another. This is not the same test as touching spikes. Both need checking after a visual change because a new silhouette can change what a landing appears to mean. The observed retry works; whether the failure reads clearly is still a human judgment.",'fall','fall-retry'),
            ('Keep the small forgiveness windows',"Here the jump input arrives just after leaving a ledge, and the character still rises. This is the starter's coyote window, not a new Clawd power. The recording demonstrates this particular late jump. Boundary tests separately check the accepted and expired tick ages; one attractive replay does not prove every timing case.",'coyote','coyote'),
            ('An early press can be remembered',"Now Space arrives before landing, and the buffered request produces the next jump. The controller consumes that request once. This is different from holding a key forever. Keeping the original input behavior gives us a stable baseline while we inspect the new character. The art is the experiment; the jump rules are not.",'buffer','buffer'),
            ('Pause is not another animation',"Escape pauses the jump, Enter resumes, and R restarts. The capture also sends a labelled simulated focus-loss event, returns to the menu, and starts again. Pause freezes the animation clock as well as the player's motion. These scripted checks demonstrate the recorded controls, not an unstated human usability test.",'pause','pause-resume-restart-focus-menu'),
            ('The mouse path still works',"The menu's button also resumes and starts the game with mouse input. It is easy to check only the keyboard path you usually use. A small revision deserves a small but deliberate regression pass: does the rest of the existing interface still do what it did before?",'mouse','mouse-menu'),
            ('Finish this course, then replay',"Clawd clears the original steps and gaps, reaches the same finish, and celebrates. Enter starts a fresh run. This recorded route completes without a death. It is not yet the proposed agentic-loop game: the flag is still the original flag. Keeping that distinction visible is part of explaining what we actually built.",'finish','finish-camera-hud-replay')]:
            bid=add(heading,text,take=take);features.append((feature,take,bid))
    else:
        add('The same scene, a new presentation layer',"The project still starts from main dot t s c n. The session constructs platforms, hazards, player, camera, and a separate interface layer. Clawd art is a drawing helper called by the player. There is no imported sprite sheet, AnimationPlayer node, or hidden agent service. The coding agent is the character's theme, not an autonomous player.",'GodotDevWorkbench',{'mode':'tree','title':'Same game owners; one new art helper','project':'walker-jumpman-clawd','source':'Source-backed runtime anatomy · game/main.tscn + session.gd','treeLabel':'Runtime construction, not a captured Remote dock','tree':['WalkerJumpman — session.gd','  Platforms / hazards / finish','  Player — player.gd','    CollisionShape2D','  Camera2D','  CanvasLayer → HUD'],'notes':[{'label':'New helper','value':'clawd_art.gd: drawing only'},{'label':'Unchanged data','value':'first_steps.json + tuning.gd'}],'output':['Library gallery is a separate scene.']})
        b=code('Keep collision separate from the art',"The rectangle shape is eighteen by twenty-eight, centered fourteen units above the player's origin. That places the reference at the feet. We preserved this code. Changing the picture does not change this collider, and testing the drawing alone cannot establish that the visual boundary feels fair.",'features/player/player.gd','var shape := RectangleShape2D.new()','add_child(collider)',[('Preserved contract','18 × 28; origin at feet'),('Inspect next','Wide art versus narrow physics')])
        result(b,'See the mismatch before fixing it',"The blue outline is the collision reference; the orange arms extend beyond it. Both views are enlarged, staged Godot drawings, not gameplay. We have exposed the design question instead of quietly widening the collider. That would change which hazards and landings collide, so it deserves its own prediction and regression tests.",'inspector')
        b=code('Choose the pose from real state',"This selector reads the session result, then grounded state and horizontal speed. Completion celebrates, failure uses error, air uses the jump pose, and speed chooses walk or run. These names do not add inputs. Run is an animation at the existing speed, not a new sprint button.",'features/player/player.gd','func visual_animation()','return "idle"', [('Source of truth','Session + floor + velocity'),('Not implemented','Sprint, crouch input, or powers')])
        # Include the whole compact selector, not only its first early return.
        e=excerpts[-1];lines=(GAME/'godot/features/player/player.gd').read_text().splitlines();e['end_line']=next(i for i in range(e['start_line'],len(lines)) if lines[i]=='\treturn "idle"')+1;e['text']='\n'.join(lines[e['start_line']-1:e['end_line']]);beats[-1]['shot']['remotion']['props']['code']=e['text']
        result(b,'The selected pose follows the movement',"Watch Clawd start, move, brake, and stand still. The faster leg motion belongs to the existing velocity; it is not driving the body. The controller remains authoritative. The capture exercises both directions and opposing inputs. Judge the silhouette while it moves, not only when a character sheet looks tidy.",'controls')
        b=code('Do not draw a second jump arc',"The paint helper treats airborne rendering specially. It samples the library's apex pose, then removes the gallery's decorative vertical jump offset. The CharacterBody supplies the actual trajectory. Without that separation, the drawing could appear to hop independently of the collider, making a valid landing look wrong.",'features/player/clawd_art.gd','var s := sample("jump"','if airborne: s.y',[('Animation','Held apex pose'),('Motion','Existing CharacterBody2D physics')])
        result(b,'Physics carries the visible jump',"The character takes off and lands once. Holding the button does not cause another jump, and the midair press does not add a double jump. The new art stays attached to the body's trajectory. This is the visible consequence of separating display animation from the game's physical movement.",'jump')
        b=code('Session state owns failure and success',"This small read-only method translates the existing session state into presentation context. Complete, failed, and paused are descriptions for the drawing layer. The method does not change state, grant completion, or postpone a retry. Keeping ownership here prevents a missing or slow animation from deciding whether the game recovers.",'game/session.gd','func player_animation_context()','return "playing"',[('Direction','Game state → presentation'),('No reverse control','Animation does not end the attempt')])
        result(b,'The error animation does not own retry',"Clawd reaches the spike, reacts, and returns to the start on the existing timer. The brief error animation does not have to finish before the game can reset. This is a small example of a useful boundary: presentation describes the outcome; the session decides the outcome.",'spike')
        b=code('Freeze the presentation clock on pause',"The frame update returns immediately when the session says paused. Otherwise it chooses a pose, resets the animation clock on a pose change, advances time, and requests a redraw. None of those lines update velocity or collision. Pause therefore freezes the pose without replacing the original player physics function.",'features/player/player.gd','func _process(delta: float)','queue_redraw()', [('Clock','Display time, not physics tick'),('Pause','Return before advancing time')])
        result(b,'Paused means the pose stops too',"The jump and its pose hold during pause, then resume. The captured sequence also retries and returns to the menu, with focus loss explicitly simulated. Machine checks support these observations. A human still needs to judge whether the controls and feedback are understandable; a passing script is not that judgment.",'pause')
        b=code('The level still comes from the same data',"The solids, hazard, and finish coordinates are unchanged. The session builds their collision and drawing; its camera follows the player within the same bounds. The interface still displays the original progress and retry information. No task checkpoint was added just because the character now represents a coding agent.",'levels/first_steps.json','"solids"','"finish"',[('Preserved','Layout, camera, HUD and finish'),('Later','Mini-goals and level extension')])
        result(b,'The old course still completes',"Follow the unchanged route to the flag. The camera scrolls, the progress bar advances, and completion offers replay. Clawd celebrates, but this is the starter's finish condition. The future full-loop goal requires new state, reset rules, tests, and a design decision. Today we have evidence for this route only.",'finish')
        board('Tests have different jobs',"The original twenty-five mechanics checks and nine keyboard checks pass. A separate test compares a hundred sixty-two animation samples with Brutalist's TypeScript reference and checks presentation selection. These are machine checks, including staged fixtures. The recording driver uses normal input instead. Neither kind proves that Bear likes the character or that another player understands it.",[['Mechanics and input','25 original checks + 9 keyboard checks'],['Animation reference','162 sampled comparisons + presentation checks'],['Human review','Readability, fairness, and the next decision']], 'evidence/clawd/ · godot/tests/ · scripted captures have their own receipts')
    board('Start early; keep the honest trail',"A first scene can appear quickly. Refinement is where the work continues. Make an improvement today; come back for another improvement or test in the next session. If an attempt does not work, record what you tried, observed, and learned in Frictional. Do not manufacture struggle or pretend these changes happened across several days. This iteration's entries are from one actual session.",[['Actual effort','Intent → attempt → observation'],['Useful failure','What did not work, and what it ruled out'],['Next session','One improvement or test; record human and AI work']], 'FRICTIONAL.md · honest evidence, not an hours contest')
    board('The larger idea stays on the roadmap',"Bear's longer-term idea is a coding agent crossing mini-goals: a task completed, another task checked, and eventually a full agentic loop finished. Those are design notes, not features in today's build. The level extension is still required for Assignment One. Starting with Clawd's appearance lets Bear decide the next step from something he can actually play.",[['Now','Character in the existing level'],['Later','Task mini-goals → completed agentic loop'],['Not finished','Level extension and final Assignment 1 submission']], 'CHANGE-BRIEF.md · proposed direction, not gameplay evidence')
    if kind=='gamedev':
        b=code('One catalogue feeds a separate gallery',"The gallery chooses six names for its current page and calls the same painting helper used by the player. This keeps the preview connected to the real implementation. The next three pages show all eighteen available animations. Only the smaller state-driven subset is connected to gameplay; a preview does not create an ability.",'gallery/clawd_gallery.gd','var animation: String','Art.paint(self',[('Same renderer','Player and gallery share ClawdArt'),('Separate purpose','Visual catalogue, not new controls')])
    gallery=[('Gallery 1: idle through run',"Idle, bounce, wave, look, walk, and run. Watch the four legs alternate and the eyes scan. These are actual Godot gallery previews of the ported library. Bounce and wave are available artwork, not player commands in this level. The gallery lets us judge options before choosing more behavior.",'gallery-one'),('Gallery 2: thought and reaction',"Think, type, sleep, error, nod, and shake. Their names suggest possible future coding-agent moments, but naming an animation does not implement a task system. Error currently reacts to failure; the others remain catalogue options. Choose a future state for a reason, then test whether the animation communicates it.",'gallery-two'),('Gallery 3: motion and celebration',"Dance, stretch, crouch, jump, spin, and celebrate. Spin flips horizontally instead of rotating the pixel rectangles. The gallery jump is decorative; gameplay uses its held pose while physics moves the body. Celebrate is connected to the current finish. All eighteen are here to inspect, not a promise of eighteen powers.",'gallery-three')]
    for i,(heading,text,take) in enumerate(gallery):
        bid=result(b,heading,text,take) if kind=='gamedev' and i==0 else add(heading,text,take=take)
        features.append(('animation-library-'+str(i+1),take,bid))
    add('The verdict',"The verdict: one recognizable character change, preserved mechanics, and a visible question about collision. The A I wrote and tested the implementation; Bear supplied the intent and chooses what deserves another iteration. Start early enough to inspect the result. A test that reveals a problem can move the project forward without making the feature complete.",'ClaudeVerdictArtifact',{'artifactTitle':'Iteration 1 · verdict','artifactHeading':'One change you can inspect','artifactLines':['Clawd is in the existing level.','Original mechanics remain the baseline.','Wide art versus collision needs human judgment.','Mini-goals and the level extension come later.']})
    turn='Please inspect walker-jumpman-clawd.\nPropose one visual improvement and one test.\nPreserve the mechanics and log the result in Frictional.'
    props=composer(turn,'Your turn · review before another change');props['greeting']='Your turn.'
    add('Your turn',"Your turn. Please inspect Walker Jumpman Clawd. Propose one visual improvement and one test. Preserve the mechanics and log the result in Frictional. Before accepting the change, check that it answers a specific observation, leaves the existing controls intact, and names what the test does not establish. Then let a human play. Liam, in for Professor Bear.",'ClaudeComposerAsk',props)
    add('Regular outro','', 'ClaudeTitleOutro',{'title':title,'slug':root.name})
    sheet={'metadata':{'slug':root.name,'title':title,'persona':'Liam','palette':'claude','engine':'kokoro','voice':'am_onyx','voice_kokoro':'am_onyx','fps':30,'width':3840,'height':2160,'aspect_ratio':'16:9','caption_policy':'SRT sidecar; no burned captions','fit':'pad','skill':'godot-waikthrough' if kind=='walkthrough' else 'godot-gamedev','modifier':'walker','human_review_approved':False,'authorization':'Bear requested the Clawd iteration and both Liam films. Local free render for review; no YouTube publication.'},'beats':beats}
    write(root/'beat_sheet.json',sheet)
    write(root/'evidence/feature-beats.json',features)
    if kind=='gamedev':
        files=[]
        for p in sorted((GAME/'godot').rglob('*')):
            if p.is_file() and '.godot' not in p.parts and p.suffix!='.uid':files.append({'path':p.relative_to(GAME/'godot').as_posix(),'sha256':sha(p),'role':'source or test support','component_ids':['iteration']})
        write(root/'gamedev-evidence.json',{'schema_version':1,'teaching_contract':'code-then-result-v1','files':files,'exclusions':[],'components':[{'id':'iteration','files':[f['path'] for f in files],'beat_ids':[b['beat_id'] for b in beats[3:-3]],'explanation':'Runtime scene ownership, player/art/collider, state/clock, level/camera/HUD, numeric reference, staged tests, keyboard tests and route helpers are explained with explicit evidence boundaries.'}],'excerpts':excerpts,'code_result_pairs':pairs})
    (root/'SCRIPT.md').write_text('# '+title+'\n\n'+''.join('## '+b['beat_id']+' — '+b['heading']+'\n\n'+(b['narration_text'] or '[Stock outro music only.]')+'\n\n' for b in beats))
    (root/'SHOTLIST.md').write_text('# Shot list\n\n'+''.join('- '+b['beat_id']+' · '+b['heading']+' · '+b['shot']['type']+'\n' for b in beats))
    (root/'FACTCHECK.md').write_text('# Source audit\n\nNarration follows CHANGE-BRIEF.md, FRICTIONAL.md and the exact new Godot source. Original physics function, tuning, level JSON and HUD are byte-identical to the starter. Mechanics: 25 checks, keyboard: 9 checks; animation: 162 independent sample points with 1,944 scalar comparisons and six staged presentation checks. No human playtest, new mini-goals, level extension or completed assignment is claimed. Gallery previews and suggested Claude prompts are labelled; their existence is not evidence of gameplay powers or a recorded chat. Capture identity, media hashes and edit decisions are checked before final assembly.\n')
    (root/'SOURCES.md').write_text((GAME/'SOURCES.md').read_text()+'\nFilm: AI-authored Liam script, local Kokoro am_onyx narration, Brutalist Claude/Godot bookends and actual native Godot captures. Human visual/film approval is pending. No paid calls or video publication.\n')
    (root/'PROMPTS.md').write_text('# Prompt provenance\n\nBear asked for one Clawd character change, all animations at the end, and two Liam explainers. The Claude composer bookends are suggested prompts, not a historical chat. No generated media service is used.\n')
    (root/'BUILD-PROMPT.md').write_text('# Rebuild this Clawd iteration film\n\nUse Brutalist godot-'+('waikthrough' if kind=='walkthrough' else 'gamedev')+' with Walker bookends and Liam. Verify source and capture hashes; preserve the original starter. Use local Kokoro, audio lock, actual normal-input Godot takes, and separately labelled diagnostic gallery. Show code then its actual result. Measure durations; never stretch gameplay. Render through scripts/build.py and the canonical remotion_scenes.py/compile.py pipeline at 3840×2160, 30 fps. Run coverage/source, frame-level visual, audio-preservation and SRT checks. Inspect all sampled frames, correct defects, record limits. Keep regular outro music only. No publishing.\n')
    (root/'SHOPPING.md').write_text('# Assets\n\nFree local pipeline only: actual Godot captures, source-backed reconstructed editor, Claude bookends, bundled fonts and regular stock outro. No paid assets or missing visual placeholders.\n')
    print(kind,len(beats),'beats',len(pairs),'code/result pairs',sum(len(b['narration_text'].split()) for b in beats),'words')
